include: package:very_good_analysis/analysis_options.yaml

analyzer:
    exclude:
        - build/**
        - lib/**/*.g.dart
        - lib/bridge_generated.dart
        - lib/bridge_generated.freezed.dart
linter:
    rules:
        public_member_api_docs: false
