name: tookey
description: Asset and access management protocol

publish_to: none # Remove this line if you wish to publish to pub.dev

version: 1.3.1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    appcheck: ^1.0.6
    build_runner: ^2.2.0
    crypto: ^3.0.2
    cupertino_icons: ^1.0.2
    dio: ^4.0.6
    ffi: ^2.0.1
    file_picker: ^5.0.1
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.0.2
    flutter_rust_bridge: ^1.34.2
    flutter_secure_storage: ^6.0.0
    flex_color_scheme: ^6.1.1
    fluttertoast: ^8.1.1
    freezed: ^2.1.0+1
    freezed_annotation: ^2.1.0
    http: ^0.13.5
    json_annotation: ^4.7.0
    local_auth: ^2.1.2
    mobile_scanner: ^2.0.0
    path: ^1.8.1
    path_provider: ^2.0.11
    provider: ^6.0.3
    sentry_flutter: ^6.18.3
    share_plus: ^6.3.0
    sse_client: ^0.1.0
    uni_links: ^0.5.1
    universal_html: ^2.0.8
    very_good_analysis: ^3.1.0
    wallet_connect: ^1.0.2
    web3dart: ^2.5.0
    flutter_svg: ^1.1.6

dev_dependencies:
    ffigen: ^7.2.2
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    json_serializable: ^6.5.4

flutter:
    uses-material-design: true
    assets:
        - .env

    fonts:
        - family: Kodachi
          fonts:
            - asset: assets/fonts/Kodachi.ttf
            
