name: tookey
description: Asset and access management protocol

publish_to: none # Remove this line if you wish to publish to pub.dev

version: 1.4.0

environment:
  sdk: ">=3.0.0"

dependencies:
    appcheck: ^1.0.6
    build_runner: ^2.2.0
    cached_annotation: ^1.6.0
    crypto: ^3.0.2
    cupertino_icons: ^1.0.2
    decimal: ^2.3.2
    dio: ^5.0.1
    ffi: ^2.0.1
    file_picker: ^5.0.1
    flex_color_scheme: ^7.0.5
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.0.2
    flutter_rust_bridge: ^1.68.0
    flutter_secure_storage: ^8.0.0
    flutter_svg: ^2.0.0
    fluttertoast: ^8.1.1
    freezed: ^2.1.0+1
    freezed_annotation: ^2.1.0
    http: ^0.13.5
    intl: ^0.18.0
    json_annotation: ^4.7.0
    local_auth: ^2.1.2
    mobile_scanner: ^3.0.0
    path: ^1.8.1
    path_provider: ^2.0.11
    provider: ^6.0.3
    rational: ^2.2.2
    sentry_flutter: ^7.7.0
    share_plus: ^7.0.2
    sse_client: ^0.1.0
    uni_links: ^0.5.1
    universal_html: ^2.0.8
    url_launcher: ^6.1.9
    very_good_analysis: ^4.0.0+1
    wallet_connect: ^1.0.2
    web3dart:
        path: ./packages/web3dart

dev_dependencies:
    cached: ^1.6.0
    ffigen: ^8.0.0
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    json_serializable: ^6.5.4

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/networks.json

    fonts:
        - family: Kodachi
          fonts:
            - asset: assets/fonts/Kodachi.ttf
            
