#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.51.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_connect_logger_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "connect_logger",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| connect_logger(task_callback.stream_sink()),
    )
}
fn wire_to_public_key_impl(
    port_: MessagePort,
    key: impl Wire2Api<String> + UnwindSafe,
    _compressed: impl Wire2Api<bool> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "to_public_key",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_key = key.wire2api();
            let api__compressed = _compressed.wire2api();
            move |task_callback| to_public_key(api_key, api__compressed)
        },
    )
}
fn wire_to_ethereum_address_impl(port_: MessagePort, key: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "to_ethereum_address",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_key = key.wire2api();
            move |task_callback| to_ethereum_address(api_key)
        },
    )
}
fn wire_transaction_to_message_hash_impl(port_: MessagePort, tx_request: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "transaction_to_message_hash",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_tx_request = tx_request.wire2api();
            move |task_callback| transaction_to_message_hash(api_tx_request)
        },
    )
}
fn wire_message_to_hash_impl(port_: MessagePort, data: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "message_to_hash",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_data = data.wire2api();
            move |task_callback| message_to_hash(api_data)
        },
    )
}
fn wire_encode_message_sign_impl(
    port_: MessagePort,
    data: impl Wire2Api<String> + UnwindSafe,
    chain_id: impl Wire2Api<u32> + UnwindSafe,
    signature: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "encode_message_sign",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_data = data.wire2api();
            let api_chain_id = chain_id.wire2api();
            let api_signature = signature.wire2api();
            move |task_callback| encode_message_sign(api_data, api_chain_id, api_signature)
        },
    )
}
fn wire_encode_transaction_impl(
    port_: MessagePort,
    tx_request: impl Wire2Api<String> + UnwindSafe,
    signature: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "encode_transaction",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_tx_request = tx_request.wire2api();
            let api_signature = signature.wire2api();
            move |task_callback| encode_transaction(api_tx_request, api_signature)
        },
    )
}
fn wire_keygen_impl(port_: MessagePort, params: impl Wire2Api<KeygenParams> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "keygen",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_params = params.wire2api();
            move |task_callback| Ok(mirror_KeygenResult(keygen(api_params)))
        },
    )
}
fn wire_sign_impl(port_: MessagePort, params: impl Wire2Api<SignParams> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "sign",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_params = params.wire2api();
            move |task_callback| Ok(mirror_SignResult(sign(api_params)))
        },
    )
}
// Section: wrapper structs

#[derive(Clone)]
struct mirror_KeygenResult(KeygenResult);

#[derive(Clone)]
struct mirror_SignResult(SignResult);

// Section: static checks

const _: fn() = || {
    {
        let KeygenResult = None::<KeygenResult>.unwrap();
        let _: Option<String> = KeygenResult.key;
        let _: Option<String> = KeygenResult.error;
    }
    {
        let SignResult = None::<SignResult>.unwrap();
        let _: Option<String> = SignResult.result;
        let _: Option<String> = SignResult.error;
    }
};
// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}

impl Wire2Api<u16> for u16 {
    fn wire2api(self) -> u16 {
        self
    }
}
impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for mirror_KeygenResult {
    fn into_dart(self) -> support::DartAbi {
        vec![self.0.key.into_dart(), self.0.error.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_KeygenResult {}

impl support::IntoDart for mirror_SignResult {
    fn into_dart(self) -> support::DartAbi {
        vec![self.0.result.into_dart(), self.0.error.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_SignResult {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
